// Generated by CoffeeScript 1.4.0
(function() {
  var americano, port;

  americano = require('americano');

  port = process.env.PORT || 31436;

  americano.start({
    name: 'Feeds',
    port: port
  });

}).call(this);
