// Generated by CoffeeScript 1.6.3
var americano;

americano = require('americano-cozy');

module.exports = {
  feed: {
    all: function(doc) {
      return emit(doc.tags, doc);
    }
  },
  param: {
    all: function(doc) {
      return emit(doc.name, doc);
    }
  }
};
